### ISSUE TITLE
Quansight Repository Code of Conduct

### ISSUE THREAD

**Issue by kcpevey** [Quansight/.github#2]
# Quansight Repository Code of Conduct

1. Quansight Repository Code of Conduct Introduction
  a. Expected Behavior
  b. Unacceptable Behavior
2. Incident Reporting Guidelines
  a. How to Submit a Report
  b. Conflicts of Interest
  c. What to Include in a Report
  d. Procedure after Filing a Report
3. License  
  
------- 

## 1. Quansight Repository Code of Conduct Introduction

This Code of Conduct aims to empower all users, maintainers, and contributors of Quansight public repositories and open source projects to facilitate healthy and constructive community behavior. It outlines expectations for participation in Quansight-managed public repositories, as well as steps for reporting unacceptable behavior. 

This code of conduct applies to all repos and communities for Quansight-managed open source projects regardless of whether or not the repository explicitly calls out its use of this code. The code also applies in public spaces when an individual is representing a project or its community. Examples include using an official project e-mail address, posting via an official social media account, or acting as an appointed representative at an online or offline event. Representation of a project may be further defined and clarified by project maintainers.

We are committed to providing a welcoming and inspiring community for all. Anyone claiming affiliation with Quansight public repositories is required to conform to the Code of Conduct. This Code of Conduct applies to all spaces and public repositories of Quansight on platforms including Github, Gitlab, and Bitbucket. People violating this code of conduct may be banned from the community. 

The Quansight Labs Co-Directors can be contacted by emailing `coc@quansight.com`. All reports will be reviewed and will be kept confidential.

### a. Expected Behavior

  * Be empathetic, welcoming, friendly, and patient. We believe that everyone deserves to be treated with kindness and empathy. 
  * Be considerate and mindful. Your work will be used by other people and you will depend on the work of others. Any decision you take will affect users and colleagues and you should take those consequences into account when making decisions. Remember that you might not be communicating in someone else’s primary language. If something is not clear, respectfully ask for clarification.
  * Offer to help if you see someone struggling, or otherwise, in need of assistance by taking care and being kind without being patronizing. If someone approaches you looking for help, try to be generous with your time; if you do not have the time to help, direct them to someone else who may be of assistance.
  * Be mindful of the words that you choose. Do not insult or put down others. Take responsibility for our own speech. 
  * Be respectful toward remote and in person interactions alike. Adopt habits that are inclusive and productive for community members wherever and whoever they are.
  * Be polite and friendly in all forms of communication, especially written communication, where opportunities for misunderstanding are greater. Use sarcasm carefully. Tone is hard to decipher online; thus, make judicious use of emoji to aid in communication. 
  * Our community consists of people from a wide range of backgrounds. Different people have different perspectives on issues. Disagreements, both social and technical, are useful learning opportunities. Seek to understand the other viewpoints and resolve differences constructively. Being unable to understand why someone holds a viewpoint doesn’t mean that they’re wrong.

### b. Unacceptable Behavior

Do not insult or put down other members of the community. Do not tolerate behavior that is disrespectful to anyone or that excludes, intimidates, or causes discomfort to others. Do not tolerate discrimination or harassment based on characteristics that include, but are not limited to, gender identity and expression, sexual orientation, disability, physical appearance, body size, citizenship, nationality, ethnic or social origin, pregnancy, familial status, veteran status, genetic information, religion or belief (or lack thereof), membership of a national minority, property, age, education, socio-economic status, technical choices, and experience level.

Behaviors that we consider harassment and exclusionary include but are not limited to:   

* Violent threats or language directed against another person
* Posting sexually explicit or violent material
* Posting (or threatening to post) other people's personally identifying information ("doxing")
* Sharing private content, such as emails sent privately or non-publicly, or direct message history, without the sender’s consent
* Personal insults, especially those using racist or sexist terms
* Unwelcome sexual attention
* Public or private harassment
* The use of sexualized language or imagery
* Excessive profanity (please avoid curse words; people differ greatly in their sensitivity to swearing)
* Sexist, racist, or otherwise discriminatory jokes and language
* Trolling or insulting and derogatory comments
* Comments which have the effect of excluding people on the basis of membership in a specific group, including the level of experience, gender, gender identity and expression, sexual orientation, disability, neurotype, personal appearance, body size, race, ethnicity, age, religion, or nationality
* Continuing to initiate interaction (such as photography, recording, messaging, or conversation) with someone after being asked to stop
* Other unethical or unprofessional conduct
* Advocating for, or encouraging, any of the above behaviors

This Code of Conduct is not exhaustive or complete. It serves to capture our common understanding of a productive, collaborative environment. We expect the code to be followed in spirit as much as in the Code of Conduct. 

## 2. Incident Reporting Guidelines

We encourage all communities to resolve issues on their own whenever possible. This builds a broader and deeper understanding and ultimately a healthier interaction. In the event that an issue cannot be resolved locally and someone is violating the Code of Conduct, please feel free to report your concerns by contacting the Quansight Labs Co-Directors.  The Code of Conduct violations reduce the value of our community for everyone. Quansight takes reports of misconduct very seriously and is committed to preserving and maintaining the welcoming nature of our open source community culture.

**All reports will be kept confidential.**

In some cases, Quansight may determine that a public statement will need to be made. If that’s the case, the identities of all involved parties and reporters will remain confidential unless those individuals instruct us otherwise.

All complaints will be reviewed and investigated and will result in a response that is deemed necessary and appropriate to the circumstances. Quansight commits to maintaining confidentiality with regard to the reporter of an incident.

For possibly unintentional breaches of the Code of Conduct, you may want to respond to the person and point out this Code of Conduct (either in public or in private, whatever is most appropriate). If you would prefer not to do that, please report the issue to the maintainer of the repository in question or to the Quansight Labs Co-Directors directly. Alternatively, you can reach out to the Quansight Diversity and Inclusion Committee for advice in confidence  at `coc@quansight.com`. 

Be an active bystander and inform Quansight if you notice a dangerous situation or violations of this Code of Conduct, even if they seem inconsequential.

### a. How to Submit a Report

In the context of this Code of Conduct, a “report” means reporting any incidents 
of Code of Conduct violations either verbally or in writing. 

Quansight is committed to promptly addressing any reported issues. If you have experienced or witnessed behavior that violates the Quansight Repository Code of Conduct, please report it in a timely manner. 

**In your report please include:**

  * Your contact information.
  * Names (real, usernames or pseudonyms) of any individuals involved. If there are additional witnesses, please include them as well.
  * Your account of what occurred, and if you believe the incident is ongoing. If there is a publicly available record (e.g. a mailing list archive or a public chat log), please include a link or attachment.
  * Any additional information that may be helpful.

All reports will be reviewed and will result in a response that is deemed necessary and appropriate to the circumstances. Where additional perspectives are needed, the team may seek insight from others with relevant expertise or experience. The confidentiality of the person reporting the incident will be kept at all times. Involved parties are never part of the review team.

Anyone asked to stop unacceptable behavior is expected to comply immediately. If an individual engages in unacceptable behavior, the review team may take any action they deem appropriate, including a permanent ban from the community.

### b. Conflicts of Interest

In the event of any conflict of interest, the community member will immediately notify the Quansight.

If you are concerned about making a report that will be read or heard by any specific individual, please reach out to Quansight Labs Co-Directors. 

### c. What to Include in a Report
Our ability to address any code of conduct breaches in a timely and effective manner is impacted by the amount of information you can provide. You can include as much of the following information as you can when you report:

  * Your preferred medium of contact. If you wish to remain anonymous, your information will not be shared beyond the person receiving the initial report.
  * The approximate time and location of the incident (please be as specific as possible)
  *  Identifying information (e.g. name, nickname, screen name, physical description) of the individual whose behavior is being reported
  * Description of the behavior (if reporting harassing language, please be specific about the words used), your account of what happened, and any available supporting records (e.g. email, GitHub issue, screenshots, etc.)
  * Description of the circumstances/context surrounding the incident
  * Let us know if the incident is ongoing, and/or if this is part of an ongoing pattern of behavior
  * Names and contact info, if possible, of anyone else who witnessed or was involved in this incident. (Did anyone else observe the incident?)
  * Any other relevant information you believe we should have

### d. Procedure after a Report

**Reviewing the Report**
The Quansight CoC Committee will make all efforts to review the incident within three days and determine:
 
* Whether this is an ongoing situation, or if there is a threat to anyone’s physical safety
* What happened
* Whether this event constitutes a code of conduct violation
* Who the bad actor was if any

If the incident took place in person or within the online channels of a Quansight platform, the Quansight CoC Committee will reach out to the relevant parties as necessary to follow up on the incident.

**Contacting the Person Reported**
After the Quansight CoC Committee has had time to review and discuss the report, someone will attempt to contact the person who is the subject of the report to inform them of what has been reported about them. We will then ask that person for their account of what happened.

 
**Response and Potential Consequences**
Once the Quansight CoC Committee has completed its investigation of the report, we will make a decision as to how to respond. The person making a report will not normally be consulted as to the proposed resolution of the issue, except insofar as we need to understand how to help them feel safe.

Potential consequences for violating the Quansight Code of Conduct include:

* Nothing (if it is determined that no violation occurred)
* Private feedback or reprimand from Quansight to the individual(s) involved
* Warning the person to cease their behavior and that any further reports will result in sanctions
* A public announcement that an incident occurred
* Mediation (only if both reporter and reportee agree)
* An imposed vacation 
* A permanent or temporary ban from some or all Quansight spaces (mailing lists, GitHub repos, in-person events, etc.)
* Assistance to the complainant with a report to other bodies, for example, institutional offices or appropriate law enforcement agencies
* Removing a person from Quansight employment or other formal affiliation
* Publishing an account of the harassment and calling for the resignation of the alleged harasser from their responsibilities (usually pursued by people without formal authority: may be called for if the person is the event leader, or refuses to stand aside from the conflict of interest, or similar)
* Any other response that Quansight deems necessary and appropriate to the situation
* At Quansight events, if a participant engages in behavior that violates this Code of Conduct, the organizers and staff may take any action they deem appropriate

Potential consequences for violating the Quansight Code of Conduct at an in-person company event include:
* Warning the person to cease their behavior and that any further reports will result in sanctions
* Requiring that the person avoid any interaction with, and physical proximity to, the person they are harassing for the remainder of the event
* Immediately ending any event volunteer responsibilities and privileges the reported person holds
* Expelling the person from the event
* Requiring that the person immediately leave the event and not return
* Banning the person from future events (either indefinitely or for a certain time period)
* Any other response that Quansight deems necessary and appropriate to the situation

No one espousing views or values contrary to the standards of our Code of Conduct will be permitted to hold any position representing Quansight, including volunteer positions. Quansight has the right and responsibility to remove, edit, or reject comments, commits, code, edits, and other online contributions that are not aligned with this Code of Conduct.

We aim to respond within one week to the original reporter with either a resolution or an explanation of why the situation is not yet resolved. We will contact the person who is the subject of the report to let them know what actions will be taken as a result of the report if any.

Our policy is to make sure that everyone aware of the initial incident is also made aware that official action has been taken while still respecting the privacy of individuals. Quansight may choose to make a public report of the incident while maintaining the anonymity of those involved.

## 3. License

This code of conduct has been adapted from numerous sources, including TODO Group Code of Conduct template, Django Code of Conduct, Contributor Covenant, Ubuntu Code of Conduct v2.0, NumFOCUS Code of Conduct, Vox Media Code of Conduct, the Bokeh Code of Conduct, the SciPy Code of Conduct, the Carpentries Code of Conduct, and the NeurIPS Code of Conduct.

**Comment by dharhas** [comment]
Is this @asmeurer's work or the more recent DEI committee work?

**Comment by kcpevey** [comment]
This is the DEI commitee's work. @dhavide asked that I convert their work, which was in a Google doc, to markdown format.

**Comment by asmeurer** [comment]
To clarify, the CoC in #1 is not "my work". I took the NumFOCUS CoC, as suggested by some people on Slack, and replaced mentioned of "NumFOCUS" with "Quansight".

**Comment by kcpevey** [comment]
@dhavide this is ready for review.

**Comment by asmeurer** [comment]
Is this ready for review? I think this should be opened as a pull request, and #1 closed.

**Comment by kcpevey** [comment]
I'll open a PR as soon as I have write access.

**Comment by dharhas** [comment]
I'm out right now and can't work out how to give you access from the mobile app. Will do so when I'm back at a computer.

**Comment by asmeurer** [comment]
I added the developers team to the repo. I'm not sure what the right teams this repo should have are, but that should be enough to give you access for now.

**Comment by kcpevey** [comment]
PR opened #3 . Let's move discussions and edits over there.
