### ISSUE TITLE
Scope of the code of conduct

### ISSUE THREAD

**Issue by mattip** [Quansight/.github#4]
The [Introduction](https://github.com/Quansight/.github/blob/master/CODE_OF_CONDUCT.md#1-introduction) to the code of conduct needs a bit of editing. The first sentence is not clear. Additionally, it is not clear how this document relates to Quansight employees who are already bound to the Quansight employee code of conduct (reference needed). As a member of the Code of Conduct committee (for 2021) I would feel out of my depth trying to adjudge COC allegations against an employee or between two employees.

**Comment by rgommers** [comment]
> Additionally, it is not clear how this document relates to Quansight employees who are already bound to the Quansight employee code of conduct (reference needed). As a member of the Code of Conduct committee (for 2021) I would feel out of my depth trying to adjudge COC allegations against an employee or between two employees.

This CoC applies to our open source repositories and projects, and hence has a standard open source CoC flavour with anonymous incident reporting via email. This kind of reporting is not appropriate for colleagues (or in general, people who know each other personally) to begin with, and clearly the CoC committee isn't the right body for taking measures that may impact someone's employment status - that's the job of company leadership. 

I'd say that for borderline cases - e.g., someone used harsh language - apply good judgement as a committee, for anything more serious involving employees I'd say refer it to company leadership.

**Comment by mattip** [comment]
> clearly the CoC committee isn't the right body  ... 

So that should be stated.  Currently it states (under "Response and Potential Consequences") 
> An imposed vacation or removal from Quansight employment/affiliation (for Quansight personnel/affiliates)

and
> Individuals consistently engaging in behaviors contrary to the standards of our Code of Conduct will not be permitted to hold any position representing Quansight (volunteer positions included).

The former statement should refer the case to the Quansight HR department, and the latter should be rephrased to only deal with volunteer positions.
